
// CategoryList
export const CATEGORY_LIST_PAGE_LOADING = "CHATBOTADMIN_CATEGORY_LIST_PAGE_LOADING";
export const CATEGORY_LIST_PAGE_LOADED = "CHATBOTADMIN_CATEGORY_LIST_PAGE_LOADED";
export const CATEGORY_LIST_PAGE_LOADING_ERROR = "CHATBOTADMIN_CATEGORY_LIST_PAGE_LOADING_ERROR";
export const CATEGORY_LIST_PAGE_SET_CURRENT_PAGE = "CHATBOTADMIN_CATEGORY_LIST_PAGE_SET_CURRENT_PAGE";
export const CATEGORY_LIST_PAGE_SET_CURRENT_PARTITION = "CHATBOTADMIN_CATEGORY_LIST_PAGE_SET_CURRENT_PARTITION";
export const CATEGORY_LIST_PUBLISHING = "CATEGORY_LIST_PUBLISHING";
export const CATEGORY_LIST_PUBLISHED = "CATEGORY_LIST_PUBLISHED";

// Settings
export const SETTINGS_PAGE_UPDATE = "CHATBOTADMIN_SETTINGS_PAGE_UPDATE";
export const SETTINGS_PAGE_LOADING = "CHATBOTADMIN_SETTINGS_PAGE_LOADING";
export const SETTINGS_PAGE_LOADED = "CHATBOTADMIN_SETTINGS_PAGE_LOADED";
export const SETTINGS_PAGE_LOADING_ERROR = "CHATBOTADMIN_SETTINGS_PAGE_LOADING_ERROR";

// History
export const HISTORY_PAGE_LOADING = "CHATBOTADMIN_HISTORY_PAGE_LOADING";
export const HISTORY_PAGE_LOADED = "CHATBOTADMIN_HISTORY_PAGE_LOADED";
export const HISTORY_PAGE_LOADING_ERROR = "CHATBOTADMIN_HISTORY_PAGE_LOADING_ERROR";
export const HISTORY_FILTER_CHANGED = "CHATBOTADMIN_HISTORY_FILTER_CHANGED"

export const HISTORY_TBL_PAGE_CHANGE = "CHATBOTADMIN_HISTORY_TBL_PAGE_CHANGE";
export const HISTORY_TBL_PAGE_SIZE_CHANGE = "CHATBOTADMIN_HISTORY_TBL_PAGE_SIZE_CHANGE";
export const HISTORY_TBL_SORTED_CHANGE = "CHATBOTADMIN_HISTORY_TBL_SORTED_CHANGE";
export const HISTORY_TBL_FILTERED_CHANGE = "CHATBOTADMIN_HISTORY_TBL_FILTERED_CHANGE";




// CategoryListItem
export const CATEGORY_ITEM_LOADING = "CHATBOTADMIN_CATEGORY_ITEM_LOADING";
export const CATEGORY_ITEM_LOADED = "CHATBOTADMIN_CATEGORY_ITEM_LOADED";
export const CATEGORY_ITEM_LOADING_ERROR = "CHATBOTADMIN_CATEGORY_ITEM_LOADING_ERROR";
export const CATEGORY_ITEM_END_EDIT = "CHATBOTADMIN_CATEGORY_ITEM_END_EDIT";
export const CATEGORY_ITEM_SET_CURRENT_PARTITION = "CHATBOTADMIN_CATEGORY_ITEM_SET_CURRENT_PARTITION";

export const LEARNING_LOADING = "CHATBOTADMIN_LEARNING_LOADING";
export const LEARNING_LOADED = "CHATBOTADMIN_LEARNING_LOADED";
export const LEARNING_LOADING_ERROR = "CHATBOTADMIN_LEARNING_LOADING_ERROR";

export const LEARNING_PAGE_LOADING = "CHATBOTADMIN_LEARNING_PAGE_LOADING";
export const LEARNING_PAGE_LOADED = "CHATBOTADMIN_LEARNING_PAGE_LOADED";
export const LEARNING_PAGE_LOADING_ERROR = "CHATBOTADMIN_LEARNING_PAGE_LOADING_ERROR";
export const LEARNING_FILTER_CHANGED = "CHATBOTADMIN_LEARNING_FILTER_CHANGED"

export const PATTERNS_PAGE_LOADING = "CHATBOTADMIN_PATTERNS_PAGE_LOADING";
export const PATTERNS_PAGE_LOADED = "CHATBOTADMIN_PATTERNS_PAGE_LOADED";
export const PATTERNS_PAGE_LOADING_ERROR = "CHATBOTADMIN_PATTERNS_PAGE_LOADING_ERROR";
export const PATTERNS_FILTER_CHANGED = "CHATBOTADMIN_PATTERNS_FILTER_CHANGED"

export const MODEL_PAGE_LOADING = "CHATBOTADMIN_MODEL_PAGE_LOADING";
export const MODEL_PAGE_LOADED = "CHATBOTADMIN_MODEL_PAGE_LOADED";
export const MODEL_PAGE_LOADING_ERROR = "CHATBOTADMIN_MODEL_PAGE_LOADING_ERROR";
export const MODEL_FILTER_CHANGED = "CHATBOTADMIN_MODEL_FILTER_CHANGED"

// PartitionList
export const PARTITION_LIST_PAGE_LOADING = "CHATBOTADMIN_PARTITION_LIST_PAGE_LOADING";
export const PARTITION_LIST_PAGE_LOADED = "CHATBOTADMIN_PARTITION_LIST_PAGE_LOADED";
export const PARTITION_LIST_PAGE_LOADING_ERROR = "CHATBOTADMIN_PARTITION_LIST_PAGE_LOADING_ERROR";

// PartitionItem
export const PARTITION_ITEM_LOADING = "CHATBOTADMIN_PARTITION_ITEM_LOADING";
export const PARTITION_ITEM_LOADED = "CHATBOTADMIN_PARTITION_ITEM_LOADED";
export const PARTITION_ITEM_LOADING_ERROR = "CHATBOTADMIN_PARTITION_LIST_ITEM_LOADING_ERROR";
export const PARTITION_ITEM_END_EDIT = "CHATBOTADMIN_PARTITION_ITEM_END_EDIT";

// SubpartList
export const SUBPART_LIST_PAGE_LOADING = "CHATBOTADMIN_SUBPART_LIST_PAGE_LOADING";
export const SUBPART_LIST_PAGE_LOADED = "CHATBOTADMIN_SUBPART_LIST_PAGE_LOADED";
export const SUBPART_LIST_PAGE_LOADING_ERROR = "CHATBOTADMIN_SUBPART_LIST_PAGE_LOADING_ERROR";

// SubpartItem
export const SUBPART_ITEM_LOADING = "CHATBOTADMIN_SUBPART_ITEM_LOADING";
export const SUBPART_ITEM_LOADED = "CHATBOTADMIN_SUBPART_ITEM_LOADED";
export const SUBPART_ITEM_LOADING_ERROR = "CHATBOTADMIN_SUBPART_LIST_ITEM_LOADING_ERROR";
export const SUBPART_ITEM_END_EDIT = "CHATBOTADMIN_SUBPART_ITEM_END_EDIT";
export const SUBPART_ITEM_SET_PARTITION = "CHATBOTADMIN_SUBPART_ITEM_SET_PARTITION";

